export const GET_PRODUCT_LOAD="GET_PRODUCT_LOAD";
export const GET_PRODUCT_SUCCESS="GET_PRODUCT_SUCCESS";
export const GET_PRODUCT_FAIL="GET_PRODUCT_FAIL";
export const GET_PRODUCT="GET_PRODUCT";
export const POST_PRODUCT="POST_PRODUCT";
export const POST_PRODUCT_FAIL="POST_PRODUCT_FAIL";
export const DELETE_PRODUCT_FAIL="DELETE_PRODUCT_FAIL";